spring:
  application:
    name: innter-ms-people
  datasource:
    url: jdbc:mysql://${dev-db-url:localhost}:${dev-db-port:3306}/${dev-db-name-pos}
    username: ${dev-db-username-pos}
    password: ${dev-db-password-pos}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://${dev-db-url:localhost}:8761/eureka
